### ISSUE TITLE
Is the docker-engine version (1.12.2) critical?

### ISSUE THREAD

**Issue by shezzski** [dtag-dev-sec/tpotce#111]
Hi,
After a brand new installation from the prebuilt tpot.iso for T-Pot 16.10 I have noticed that the docker-engine version is 1.12.2 post scripted install, but when you "apt-get update" as of today the version is upgraded to 17.05.0-ce.

- I was wondering if there is a reason that 1.12.2 is installed?
- Is there a problem with upgrading T-Pot's docker-engine with "apt-get upgrade" to obtain the latest docker-engine?

TIA

**Comment by t3chn0m4g3** [comment]
Thanks for the info, but I cannot confirm this. We are strictly using `docker.io` from the ubuntu repositories, which is on [1.12.6](https://packages.ubuntu.com/en/xenial-updates/docker.io) which is also my result after a fresh install.
Please run `apt search docker-engine` and `ls -al /etc/apt/sources.list.d/`. If you get a hit on `docker-engine`, or see a `docker.list` something is not correct since the installer does not add the dockerpoject repos. Also please post a `uname -a`.

**Comment by t3chn0m4g3** [comment]
Considering this answered, if not please reopen.
