### ISSUE TITLE
Feature request: Option to add Heralding Honeypot

### ISSUE THREAD

**Issue by shezzski** [dtag-dev-sec/tpotce#112]
Hi, I have come across a great little honeypot for collecting credentials only, its called Heralding https://github.com/johnnykv/heralding 

I think this could be a good inclusion/substitution where desired for T-Pot.

**Comment by t3chn0m4g3** [comment]
Heralding is a really awesome honeypot, but since some of the other honeypots already support collecting credentials and thus already occupy a lot of the ports needed by heralding I currently do not see the advantage of adding it to the T-Pot core.
However, with release of 17.06 T-Pot will take leverage of docker-compose and thus will make it easier to adjust the containers to your needs.
If you find 20+ supporters I will create a docker image as an optional download for T-Pot 18.x.

**Comment by harperaa** [comment]
Any word on when 17.06 (or 17.X) will be released?

**Comment by t3chn0m4g3** [comment]
Plan on releasing Alpha soon. Check out the [Sneak Peek](https://twitter.com/marco_ochse/status/896110408322265088) :bowtie:

**Comment by t3chn0m4g3** [comment]
Heralding will be part of T-Pot 18.04.
