### ISSUE TITLE
Integration with Malware Repository Framework

### ISSUE THREAD

**Issue by zTemplar85** [dtag-dev-sec/tpotce#150]
<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? T-Pot 17.10
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? 3 days
- Did you install any upgrades or packages? Nope
- Did you modify any scripts? Nope
- Have you turned persistence on/off? Nope
- How much RAM available (login via ssh and run `htop`)? 16G
- How much stress are the CPUs under (login via ssh and run `htop`)? 12%
- How much swap space is being used (login via ssh and run `htop`)? 0
- How much free disk space is available (login via ssh and run `sudo df -h`)? 78G
- What is the current container status (login via ssh and run `sudo start.sh`)? All running well

Would like to check for future release could integration with MRF be added?
The project can be found here https://github.com/Tigzy/malware-repo

**Comment by t3chn0m4g3** [comment]
@zTemplar85 Thanks for pointing MRF (cool!) out to us, but I do not think it would make a lot of sense on T-Pot itself. Looking at the MRF specs and how it works I'm guessing a seperate machine might be better suited since I would like T-Pot's hardware requirements not going through the roof :bowtie:

**Comment by zTemplar85** [comment]
HI @t3chn0m4g3, noted on the concern with regards to hardware requirements.
