### ISSUE TITLE
Creating new honeypots

### ISSUE THREAD

**Issue by cheo2322** [dtag-dev-sec/tpotce#232]
Hi Sir, I understand that for add my owns images (honeypots) it is necessary modify /opt/tpot/etc/tpot.yml and I suppose that also I must include a new folder within /opt/tpot/docker will be the new image features. Please tell me if I am right or not, and what does mean the 'image' section for the services? For example for conpot is 
**image: "dtagdevsec/conpot:1710"**
What I should write for my own images?

**Comment by t3chn0m4g3** [comment]
Please understand this is beyond the scope of T-Pot issues / support.

`/opt/tpot/etc/tpot.yml` holds the [docker-compose](https://docs.docker.com/compose/)-config. I recommend to read up on the documentation for [docker](https://docs.docker.com/) and [docker-compose](https://docs.docker.com/compose/) before diving into your own changes. Images are provided through [docker-cloud](https://cloud.docker.com/) or you supply them locally. In each case it is necessary to provide a `repo/name:tag` based on the image you created. Since this heavily relies on docker please check out the docker documentation especially with regard to the `docker build` command and sections.

Thanks for understanding.

**Comment by cheo2322** [comment]
Thanks Sir, I appreciate your answer. Closing...
