### ISSUE TITLE
Export and import of the data

### ISSUE THREAD

**Issue by ikermuniz** [dtag-dev-sec/tpotce#240]
Hello,

I’m working with T-Pot 17.10. 
I had one remote server for a few months gathering attacks. I’ve exported the logs (scp to /data folder)

But when I import those files to my local T-Pot (for analysis), Elastic Search “captures” and shows less logs in Kibana that the ones that were in my remote server.

I’ve removed the .backup extension (just in case it gets solved) that have some logs, but the number of logs read by Elastic is still the same.

Thanks a lot for your help! 
It’s a very good project!!!

**Comment by t3chn0m4g3** [comment]
@ikermuniz The reason for this is how [logstash handles files](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html). The default mode for logstash is `tail`. You need to manually import them using `read` mode. Please dig around the issues on how to export the `logstash.conf`, adjust to your needs and import it using `volumes`.
Since T-Pot works as expected I am closing this issue.
