### ISSUE TITLE
Using 18.11 ISO tpot is not actually installed when *not* using DHCP.

### ISSUE THREAD

**Issue by LandonStewart** [dtag-dev-sec/tpotce#265]
## Issues

- [] - The TPOT stuff is not actually installed after the base system is installed.

- `CAVEAT` NOT using DHCP
- `OK` Installing Base System
- `OK` Configuring Apt
- `OK` Select and install software
- `OK` Finishing the installation
- `OK` System automagically rebooted
- `OK` I "ejected" the ISO media
- `OK` Automagically started the “Ubuntu” grub menu item
- `Problem` Saw some errors finding the ubuntu mirror during reboot
- `OK` T-Pot-Installer (choose NEXTGEN)
- `Problem` Set passwords and webui username
    - Errors
        - Got RETRY issues on some pip items
- `OK` Updated initramfs
- `Problem?` Immediately got login prompt with no reboot
- `Problem?`Checked ‘systemctl status tpot’
    - Errors:
        - Unit tpot.service could not be found.

### Basic support information

- What T-Pot version are you currtently using? 
-- 18.11 (downloaded ISO)

- Are you running on a Intel NUC or a VM?
-- Actual hardware (not a VM)

- How long has your installation been running?
-- 0 minutes

- Did you install any upgrades or packages?
-- No

- Did you modify any scripts?
-- No

- Have you turned persistence on/off?
-- No

- How much RAM available (login via ssh and run `htop`)?
-- 62GB

- How much stress are the CPUs under (login via ssh and run `htop`)?
-- zero

- How much swap space is being used (login via ssh and run `htop`)?
-- zero

- How much free disk space is available (login via ssh and run `sudo df -h`)?
-- 861GB

- What is the current container status (login via ssh and run `sudo start.sh`)?
-- sudo: start.sh: command not found

**Comment by xECK29x** [comment]
Same issue here post upgrade, looks like all the services are down.

**Comment by LandonStewart** [comment]
> Same issue here post upgrade, looks like all the services are down.

I think it's the resolvers not being used because of Ubuntu 18 uses Netplan instead of the configuration from dns-nameservers in /etc/network/interfaces.

**Comment by micoots** [comment]
Hi. To test all this, I downloaded the ISO, made sure no DHCP, installed from ISO, entered static IP when asked, and yes, the thing didn't install and the /etc/resolv.conf had:

nameserver 127.0.0.53

ie. not what was defined above in case.

I added "dns-nameserver" entry in /etc/network/interfaces, then rebooted, that did nothing just went back to the setup.

Changed /etc/resolv.conf, rebooted, that did nothing also, just went back to the setup pages.

I moved /etc/resolv.conf (since it is a symlink) and replaced it with a static /etc/resolv.conf file, which I manually added nameservers in, then rebooted, and the containers and pip etc started being pulled down and configured.

So if no DHCP is present, you're basically left with something big and broken :)

T-Pot is meant for the easy honeypot, install and forget, so this is something that either needs to be fixed or notified clearly in docs that a DHCP server is required.

**Comment by t3chn0m4g3** [comment]
@xECK29x Your comment reads if you tried to upgrade from 17.10. Did you perform a fresh install?

**Comment by xECK29x** [comment]
I eventually did just reinstall with the ISO and I’m good again. Fantastic work on this release!
  

  
  

  
  
>

**Comment by t3chn0m4g3** [comment]
I want get a grip on the described behaviour, although it seems, now that @xECK29x confirmed it working, that different phenomenons are present.

To make sure we are all on the same page... 
T-Pot requires DHCP as stated in the [Install Requirements](https://github.com/dtag-dev-sec/tpotce#requirements).
- Before the installation starts we check for the availability of any remote site we need for installation and even the Ubuntu Installer should not work if DHCP / DNS is unavailable since it installs all packages from remote.
- @LandonStewart: We are ditching `netplan` in favor of `ifupdown` even before the first boot.
- I cannot reproduce this behaviour, my standards in VMWare and VirtualBox are:
  - CPU: 2 Cores
  - RAM: 8GB
  - DISK: 128GB
  - NIC: Bridged Networking
  - NET: DHCP, DNS provided through DHCP
  - Internet: Non-filtered for tcp port 1-64000
- I also performed 10+ installs on physical hardware in the last couple of days. None showed any of the described problems with DHCP, DNS or the `pip install`.

It is possible however that this is a problem of a specific region and / or type of setup we cannot account for.

Instead of using the `tpot.iso` you can also perform the [post install method](https://github.com/dtag-dev-sec/tpotce#postinstall) which might be more suited for your specific setup. Just download Ubuntu Server 18.04 LTS, install it and use the mentioned installation method to install T-Pot on top.

**Comment by t3chn0m4g3** [comment]
@xECK29x Thanks for the great feedback! Very much appreciated :bowtie:

**Comment by t3chn0m4g3** [comment]
@micoots The file `/etc/resolv.conf` is just a stub, for `systemd-resolved`. With **resolved** in operation the linux system sends requests to 127.0.0.53 which in turn forwards DNS requests to the actual via DHCP setup DNS server. You can check the corresponding config in `/run/systemd/resolve/resolv.conf`. Also by running `systemd-resolve --status` you can get the status on the global DNS configuration from your system.

@LandonStewart With `systemd-resolved` in place changes on `/etc/resolv.conf` might be problematic and may be overwritten at any time.

**Comment by LandonStewart** [comment]
Thank you @micoots for replicating this as I described it.  

Final note - I recognize that the docs say DHCP is required however since I installed TPOT 17 using the ISO without issues while not using DHCP I hoped I could do the manual network configuration with TPOT 18 as well.  It mostly worked out except for the name servers provided during the install not being used.  It didn't quite work out the same.  In the future I'll use the post install method as mentioned by @t3chn0m4g3.

**Comment by t3chn0m4g3** [comment]
To wrap this up. If you want to set up static IP addresses on the T-Pot ISO install you should be good by following this example by editing `/etc/network/interfaces`:
```

auto ens33
iface ens33 inet static
        address 192.168.1.100
        netmask 255.255.255.0
        gateway 192.168.1.1
        dns-nameservers 192.168.1.1 8.8.8.8
```

**Comment by camaro23** [comment]
Hey Guys,

I have installed 18.11 LEGACY version and am attempting to set a static IP. I have configured /etc/network/interfaces, as shown by the example, to fit my environment. It is able to retain the static IP, however, is still not communicating with my nameservers. With it being 18.04, I see online that static network settings need to be implemented via netplan. @t3chn0m4g3 states that all config can be done via etc/network/interfaces (I have succesffully configured this on 17.10 Tpot) but I am having trouble here. Is there something I am missing?
Thanks for the help.

**Comment by LandonStewart** [comment]
Rename /etc/resolv.conf and put a new file there with your name severs lines. 

I didn’t figure it out but when I added the name server stuff to the interfaces file it didn’t work. Net plan is being used halfway or something. I did what I posted above and it worked fine.

**Comment by t3chn0m4g3** [comment]
@camaro23 Netplan is deactivated after the T-Pot installation is finished. Changing `/etc/resolv.conf` may only be a short term solution since maintainer based packages might overwrite the config again.
Netplan and Resolv Daemon, especially with Ubuntu Server, is something I am closely monitoring with regard to T-Pot. However, as recommended above, if you are looking into a long-term solution with regard to static IPs I recommend a T-Pot post install at the moment.

**Comment by t3chn0m4g3** [comment]
Please note #274.
