### ISSUE TITLE
Installation fails of T-Pot 18.11

### ISSUE THREAD

**Issue by hvdkooij** [dtag-dev-sec/tpotce#267]
Installation fails after initial network setup (DHCP).
I tried both the normal and  expert install.
The last packets seen on the network are a DNS query for archive.ubuntu.com but no actual connection to that server.
This has been verified with a packet capture on the upstream router.
In the same network I have installed T-Pot 17.10 a few times without this issue.

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using? 18.11
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? Refuses to install
- Did you install any upgrades or packages? NO
- Did you modify any scripts? NO
- Have you turned persistence on/off? NO
- How much RAM is available (login via ssh and run `htop`)? 12 GB RAM
- How much stress are the CPUs under (login via ssh and run `htop`)? N/A (4 CPU cores assigned)
- How much swap space is being used (login via ssh and run `htop`)? N/A 
- How much free disk space is available (login via ssh and run `sudo df -h`)? N/A (500GB assigned)
- What is the current container status (login via ssh and run `sudo dps.sh`)? N/A

**Comment by t3chn0m4g3** [comment]
Thanks for reporting. Unfortunately I cannot reproduce the issue. Installs work perfectly fine over here. If it already fails at network setup then it seems related to the Ubuntu Installer itself which uses `netplan` instead of `ifupdown` until we replace it after the first boot with `ifupdown` again.
Since we are using the Ubuntu Netboot Installer it might help to narrow it down using the unmodified 
[installer](http://ftp.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso).

**Comment by hvdkooij** [comment]
Ouch. Silly me. I had the old honeypot still active and it stole part of my traffic. So the new honeypot was not able to install over Internet.
After a shutdown and making sure the arp entries are clean I did another attempt and this time it starts to look much better.

**Comment by hvdkooij** [comment]
Yep. Confirmed that having 1 honeypot active will block traffic that is needed to install a new one.
So we go blind for an hour or so... big deal.

**Comment by t3chn0m4g3** [comment]
Thanks for your feedback. Enjoy 18.11 :bowtie:
