### ISSUE TITLE
dashboard and logfile

### ISSUE THREAD

**Issue by ikennarene** [dtag-dev-sec/tpotce#28]
Hi, in my dashboard i can only see honeytrap and cowrie to be active, with some counts, please how can i enable the others.  Also how to get T-Pot attack logfile. tq

**Comment by t3chn0m4g3** [comment]
the honeypots are probably active but without any events, you can check that via `sudo status.sh`; also make sure that you expose the corresponding [ports](http://dtag-dev-sec.github.io/mediator/feature/2016/03/11/t-pot-16.03.html#placement). All log files can be found in `/data` but make sure to `sudo su -` first and never change permissions in that folder.

**Comment by ikennarene** [comment]
Thanks, please how to expose the corresponding ports. Also how can i prevent my log from being deleted after honeypot services are started. Read some where by default it is restarted after 24 hours, how to prevent my logs from be remove

**Comment by schmalle** [comment]
The port forwarding depends on you environment, here we cannot help you.

**Comment by t3chn0m4g3** [comment]
turn persistence on
```
sudo su -
cd /data/
mv persistence.off persistence.on
reboot
```

**Comment by AizazAZ** [comment]
Sorry if I am asking a silly question but bare with me please. I am currently writing a Masters Thesis on this topic (plus darknet) and T-pot is my first choice of honeypot although I am using other ones as well. 

1) How can I increase persistence duration for honeypot data from 30 days (/data), persist ELK data for 90 days (/data) to like 183 days? or let's say stop collecting new data if hard disk is full, I mean don't overwrite old data.

2) Can I export all the data for later analysis? because I am doing hacker behavioral analysis in which I would need historical data very crucially. So ideally I would like to go back into some point in time and see all the attacks that were performed and other information regarding them.

Thanks.
