### ISSUE TITLE
How to backup data

### ISSUE THREAD

**Issue by pady12** [dtag-dev-sec/tpotce#287]
Hi,
 I installed the t-pot successfully, and But I don't even have a basic understanding on how backup and restore data form my T-pot and other honey-pot?
and other my question is how we have distributed sensors in other part of network and link them to primary T-pot?
Tanks a lot

**Comment by JamesBradyBear** [comment]
Sorry if I am asking a silly question but bare with me please. I am currently writing a Masters Thesis on IoT malwares and T-pot is my first choice of honeypots deployment although I am using other ones as well. I have some questions that can also be address in the same question, i guess.

How can I increase persistence duration for honeypot data from 30 days (/data), persist ELK data from 90 days (/data) to like 183 days or x days? or let's say stop collecting new data if hard disk is full, I mean don't overwrite old data.
Reference image https://github.com/dtag-dev-sec/tpotce/raw/master/doc/architecture.png

Can I export all the data for later analysis? because I am doing hacker behavioral analysis in which I would need historical data very crucially. So ideally I would like to go back into some point in time and see all the attacks that were performed and other information regarding them.

Thanks.

**Comment by t3chn0m4g3** [comment]
Backup: Go to `/opt/tpot/bin` folder and you find the dump and restore scripts which will completely backup the ES contents. This is most useful within the same T-Pot release, however not so much between releases since fields and documents are changing frequently.

Persistence: Go to `/opt/tpot/etc/logrotate` and adjust `logrotate` to your needs. All changes will have affect on how data is stored in `/data`. This works in tandem with the `/opt/tpot/bin/clean.sh`.

Persistence on ES is configured on `/opt/tpot/etc/curator/[curator, actions].yml` and triggered through `/etc/crontab`.

Logrotate usually prevents the hard disk from overflowing, however there is no quota on `/data` in place to prevent this. We had this in one of the previous releases, but usages were so different among users that we got rid of it again. You could always setup your own server and put T-Pot on top if you had a special use case like this.

**Comment by JamesBradyBear** [comment]
Thank you very much for your reply. I have change "rotate [30"] to my required value but I don't know since I don't know what does the options means. Would you please kindly refer me to some read me or explain and what other options are available for example what does "daily" means and "missingok"

[https://ibb.co/6BMkNrL](url)


Thanks.
