### ISSUE TITLE
System rebooted by itself @16.27 and stuck on this screen

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/tpotce#34]
I left the system running and all of a sudden rebooted itself with the following message

![image](https://cloud.githubusercontent.com/assets/17837413/14587819/0b701b68-04ba-11e6-87a7-28df40609be2.png)

Should I just poweroff and restart by force?

**Comment by firepro20** [comment]
It will not reboot keeps outputting that message

**Comment by t3chn0m4g3** [comment]
Reboot is by design (once a week including updates).
Block message is interesting, can you restore a recent snapshot?
If yes, ***save*** the current state and check if the error persists.
If not, ***save*** the current state and ...
```
sudo su -
apt-get dist-upgrade -y
```
If apt asks whether to replace any config files please do not!

Anyhow, it looks like some sort of a kernel problem, do the containers run flawlessly?

**Comment by firepro20** [comment]
Containers run flawlessly. I did a host restart as well just in case. What.
does the suggested command do exactly?

**Comment by t3chn0m4g3** [comment]
It not only updates packages but it may also replace them with new
versions, hence ***upgrade***.

2016-04-17 16:57 GMT+02:00 firepro20 <notifications@github.com>:
