### ISSUE TITLE
Services are down

### ISSUE THREAD

**Issue by matan1398** [dtag-dev-sec/tpotce#347]
Hi, the output of dps.sh says every service is down.
i did "systemctl start tpot" and it didnt help
i have ping to my vm
what can be the reason?

**Comment by barrydekong** [comment]
I also have the same issue and I tried to run the container but it didn't work!

**Comment by t3chn0m4g3** [comment]
Please provide more [info](https://github.com/dtag-dev-sec/tpotce/blob/master/CONTRIBUTING.MD).

**Comment by barrydekong** [comment]
I have installed Tpot 18.04. All service downed after I executed update command. It seems some service updated to 19.03. I tried to manually run the service but failed even I tried reinstall 18.04. I have installed 19.03 new version now! Besides I also found another issue when I access dashboard by port 64297 with error message "This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner"

**Comment by t3chn0m4g3** [comment]
@barrydekong Thanks for the update and sorry for the inconvenience. The error message you are receiving is because we are now enforcing TLS v1.3. You need a browser that is compatible.

**Comment by barrydekong** [comment]
Thanks for prompt reply! I have use Firefox v.66.0.3 but still with error message "Secure Connection Failed - An error occurred during a connection to 13.94.xx.xxx:64297. Peer reports incompatible or unsupported protocol version. Error code: SSL_ERROR_PROTOCOL_VERSION_ALERT
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified. Please contact the website owners to inform them of this problem."

**Comment by t3chn0m4g3** [comment]
It is a self signed certificate after all. Please check with the Firefox documentation how to accept it.

**Comment by matan1398** [comment]
![IMG_2874](https://user-images.githubusercontent.com/46320655/56089671-267c4480-5e9f-11e9-86af-88432a2dd7f6.jpg)
Hi, sorry for not answering, i arrived to the office only today.
so i've attached the dps.sh output.
i have tpot version 18.11.
what other info do you need?

**Comment by t3chn0m4g3** [comment]
[Info](https://github.com/dtag-dev-sec/tpotce/blob/master/.github/ISSUE_TEMPLATE.md).

Recommend installing 19.03.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
