### ISSUE TITLE
Adjust total number of fields to 2000

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#382]
sup @t3chn0m4g3 

just started getting this new error in Logstash today 
![image](https://user-images.githubusercontent.com/35882815/58388860-ccb48180-7fe9-11e9-96fb-1c2b67d9ec3c.png)

command ran 
`Docker logs -f logstash `

looks like I got a bunch of new fields from something that Suricata picked up and pooped out in the logs 

to fix this error 

```
PUT /logstash-*/_settings
{
"index" : {
"mapping" : {
"total_fields" : {
"limit" : "100000"
}
}
}
}
```

**Comment by iukea1** [comment]
again not an issue for most if not all people, just posting this here for people who do run across this issue.

Also thanks for updating Cowrie

**Comment by t3chn0m4g3** [comment]
Thanks. This will not fix the error entirely, also the mappings need to be updated within Kibana. I am curious what the new fields are, especially when exceeding the limit.

Within testing the number of fields was around 800. the more fields the slower the indexing. So I recommend not going beyond the 1K off too much :) Maybe start smaller i.e. 1500 and rather understand what type of event could have caused this since Suricata is pretty much straight forward regarding fields.

If you can, please share some more info regarding the event. I even would not rule out a bug.

**Comment by t3chn0m4g3** [comment]
@iukea1 The other day I did not notice, that you are only adjusting settings for existing indices. However you need to modify the template. 

The easiest way to apply the changes is using the Kibana > Devtools feature.

With regard to T-Pot this would look like this:
```
PUT _template/logstash
{
  "index_patterns": "logstash-*",
    "settings" : {
      "index" : { 
        "number_of_shards": 1,
        "number_of_replicas": 0,
          "mapping" : { 
            "total_fields" : {
              "limit" : "2000"
            } 
          }  
      }
    }
}
```

Showing the settings via `GET _template/logstash`

Modifying settings for existing indices (based on the example):
```
PUT /logstash-*/_settings
{
  "index" : { 
    "mapping" : { 
      "total_fields" : {
        "limit" : "2000"
      }
    }
  }
}
```

Reviewing settings via `GET /logstash-*/_settings`

**Comment by iukea1** [comment]
Posting an update to this here tonight.

I am currently in meetings

**Comment by iukea1** [comment]
updated "elasticsearch-templage-es6.json"

with what is below

```
{
  "template" : "logstash-*",
  "version" : 60001,
  "settings" : {
    "index.refresh_interval" : "5s",
    "index.number_of_shards" : "1",
    "index.mapping.total_fields.limit" : 2000,
    "index.number_of_replicas" : "0"
  },
```
