### ISSUE TITLE
AWS EC2 Instance fails after reboot

### ISSUE THREAD

**Issue by thearchitectofficial** [dtag-dev-sec/tpotce#455]
**Issue**
I've tried to deploy the iso image multiple times on AWS (not familiar with terraform and need to urgently get it up and running)
Everytime the final reboot takes place, the EC2 instance is unreachable over SSH and also fails the AWS System Instance Check [1/2 passed]
Would appreciate your support in getting this up and running.
---

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Debian Stretch AWS AMI
- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
NextGen and Standard both attempted

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
AWS T3.Large [2vcpus and 8 GB RAM with 150GB SSD]

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Right after final reboot system is unreachble on both 22 and 64295

- How long has your installation been running?
N/A
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
N/A
- How much free disk space is available (`df -h`)?
N/A
- What is the current container status (`dps.sh`)?
N/A
- What is the status of the T-Pot service (`systemctl status tpot`)?
N/A
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
N/A
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
N/A

**Comment by derpflanzer** [comment]
I have exactly the same issue. The whole instance is unreachable, not only port 22 and 64925.

**Comment by thearchitectofficial** [comment]
> 
> 
> I have exactly the same issue. The whole instance is unreachable, not only port 22 and 64925.

Yup, thats the thing as of now I have used Terraform to get the instance up on AWS and can establish SSH communication. However, now Im locked out of the Admin UI and Kibana dashboard also binaries like dps.sh are inaccessible even though they're present on the opt/bin path.
Shall work on this and post update, as of now why dont you too try the Terraform install?

**Comment by t3chn0m4g3** [comment]
It seems AWS EC2 is currently not compatible with the latest edition of T-Pot / Debian SID.

Please deploy a Debian Buster instance and install T-Pot on top as described in the ReadMe.

@prateepb Do you have an idea what might be the cause? (#460)

**Comment by thearchitectofficial** [comment]
> 
> 
> It seems AWS EC2 is currently not compatible with the latest edition of T-Pot / Debian SID.
> 
> Please deploy a Debian Buster instance and install T-Pot on top as described in the ReadMe.
> 
> @prateepb Do you have an idea what might be the cause? (#460)

I know this is a lame one, but there isn't a possibility for me to deploy an older version of T-Pot is there?

**Comment by thearchitectofficial** [comment]
Is there any other documentation to follow for Google Cloud deployment?

**Comment by piffey** [comment]
@thearchitectofficial I've added a PR -- which may not get accepted since it's the pre-release AMIs -- but you can reference those Buster AMIs and the install process works.

**Comment by thearchitectofficial** [comment]
> 
> 
> @thearchitectofficial I've added a PR -- which may not get accepted since it's the pre-release AMIs -- but you can reference those Buster AMIs and the install process works.



Thank you @piffey  let me take from the PR and try running an installation. Shall keep you posted on how it goes.

**Comment by thearchitectofficial** [comment]
@piffey I used the code from the PR and while now it flawlessly connects on port 22 before reboot it loses connectivity post reboot.
Also WebUI or Kibana did not come up, neither before  nor after reboot.

**Comment by piffey** [comment]
So interesting enough mine came up fine and functioned for about an hour, but fails a short interval later. Redeployed, came up fine and failed at a different interval later. Same thing happened the third time. So it's not just an issue with the install, but something afterward.

I'm going to get myself acquainted more with the internals of this project and find out if maybe there is some bug here related to that hostname issue you see or what -- perhaps something failing during the global install script, perhaps a cronjob that calls a script that then locks it up, etc.

**Comment by thearchitectofficial** [comment]
@piffey I managed to get login on the Admin UI :64294 and got this little screenshot of the tpot service restarting it may help your diagnosis.
![image](https://user-images.githubusercontent.com/55664903/66208148-0dc44d00-e6d2-11e9-8c65-34cbe5d8a27a.png)
![image](https://user-images.githubusercontent.com/55664903/66208231-3b10fb00-e6d2-11e9-8043-13afe6253358.png)

![image](https://user-images.githubusercontent.com/55664903/66207952-ad351000-e6d1-11e9-926d-7b88129166da.png)
![image](https://user-images.githubusercontent.com/55664903/66208177-1d439600-e6d2-11e9-9f79-37cef6a616be.png)

**Comment by t3chn0m4g3** [comment]
The `tpot.yml` is a symbolic link to the T-Pot edition you are running at tis missing or was deleted.

**Comment by t3chn0m4g3** [comment]
Just merged @piffey's PR at https://github.com/dtag-dev-sec/tpotce/commit/544def948157db31f572243618c68259cbeaebd8

**Comment by thearchitectofficial** [comment]
> 
> 
> The `tpot.yml` is a symbolic link to the T-Pot edition you are running and it is missing or was deleted. Without it T-Pot will not start, since it is the `docker-compose` config that tells Docker what images to run as containers and its config.
> 
> You can recreate it and link it to one of the configs in `/opt/tpot/etc/compose`.

@t3chn0m4g3  thank you for checking on this, could you tell me what the file needs to contain and can I just "nano" the file and which config should I symlink it to ?

**Comment by t3chn0m4g3** [comment]
@thearchitectofficial You can just `nano` the compose files or look the up [here](https://github.com/dtag-dev-sec/tpotce/tree/master/etc/compose).

**Comment by thearchitectofficial** [comment]
@t3chn0m4g3 and @piffey I tried to redeploy using terraform with the merged PR again and it ended giving me a fresh installation of Sid on my EC2 and not deploying Buster or Tpot at all.

Could use your help in ironing this out, kinda bummer because I thought I just had it figured out and it'd be up and running tonight.

![image](https://user-images.githubusercontent.com/55664903/66232327-38c89400-e706-11e9-89e5-d8c1f9e59a5c.png)

**Comment by t3chn0m4g3** [comment]
@thearchitectofficial `SID` is correct. The T-Pot installer will always take the current `release` version and migrate to `SID` as pointed out in the README.
As to why you end up with a non-working installation please post the `/install.log` and `/error.log`.

**Comment by thearchitectofficial** [comment]
@t3chn0m4g3  My bad on that one, it slipped my mind. I tried to install using the autoinstaller again and couldnt get it running. There were no install or error logs since the service never installed.

**Comment by t3chn0m4g3** [comment]
@piffey Can you help?

**Comment by piffey** [comment]
I've launched several instances and am digging into it further. Terraform works fine launching the instance and the cloud-init.yaml does kick off cloud init properly. The repository is checked out and the T-pot installer does run (you can observer this with `tail -f /var/log/cloud-init-output.log` when the machine first launches). It's after the install and initial reboot that I'm seeing issues with the machine becoming unresponsive. I'm still having trouble parsing out what that is, but do have some cycles to spend on it today since I need this resolved as well. I'll report back if I get any further.

**Comment by piffey** [comment]
Just to give updates since I've spent all the time I could on this today:

I looked for multiple things since it seems to be after the final reboot at some interval that the machine locks up (AWS shows 1/2 status checks, so non-responsive). I tailed all logs to see if when it locks up it gave me any data -- nothing. It also doesn't appear on any time schedule so rules out the thought I had of a possible cronjob or restart. The logs also didn't show anything failing so it's not something that is easy to find. When locking up there also isn't any spike in resources usage -- it simply stops. I've now got a few instances up and running and have killed all processes on them except docker and elasticsearch/logstash in the hopes that I can narrow it down to one of those stacks causing the problem and can drill deeper into their settings.

**Comment by thearchitectofficial** [comment]
> Just to give updates since I've spent all the time I could on this today:
> 
> I looked for multiple things since it seems to be after the final reboot at some interval that the machine locks up (AWS shows 1/2 status checks, so non-responsive). I tailed all logs to see if when it locks up it gave me any data -- nothing. It also doesn't appear on any time schedule so rules out the thought I had of a possible cronjob or restart. The logs also didn't show anything failing so it's not something that is easy to find. When locking up there also isn't any spike in resources usage -- it simply stops. I've now got a few instances up and running and have killed all processes on them except docker and elasticsearch/logstash in the hopes that I can narrow it down to one of those stacks causing the problem and can drill deeper into their settings.

Thank you for your support with this @piffey , I owe you a couple of cold ones.

**Comment by t3chn0m4g3** [comment]
@dpisano Didn't you experience some similar behaviour with DO?

**Comment by dpisano** [comment]
I did, but that was happening when I was missing `yq` form my playbooks. I have had it happen on vSphere some time too, but most of the time if I run it again it would work.

**Comment by piffey** [comment]
Well, should have gone through older posts first. Looks like it may be an issue with IPv6 being disabled as mentioned in this closed issue:

https://github.com/dtag-dev-sec/tpotce/issues/406

After re-enabling IPv6 I now have a almost two hours of uptime. I'm going to let it run over night and if that seems to have resolved it then will submit a PR that detects whether or not it is running on Amazon and then leaves IPv6 enabled if so.

**Comment by piffey** [comment]
Unfortunately no @thearchitectofficial so still digging. Leaning more and more toward it being something with network configuration however since the power status check works on Amazon, but not its detailed health check indicating that the host machine can't connect to the guest.

**Comment by thearchitectofficial** [comment]
So @piffey I tried deployments over the weekend, and they passed the health checks for AWS but again as ever the Web and Admin UI remained inaccessible.

**Comment by t3chn0m4g3** [comment]
Any updates on this?

**Comment by thearchitectofficial** [comment]
> Any updates on this?

No I haven't made any progress. How about you @piffey ?

**Comment by simonk9** [comment]
hi, i might be able to help here.
i launched a debian instance and used "Post-Install User" approach.
after reboot obviously ssh doesnt work as there is ssh honeypot instead if that is not clear.
ssh is running as documented on port 64295, in order to access it and essentially making "it" work properly, you need to modify the security group of the instance.
as mentioned under "System Placement" section, you need to open ports 1-64000 for the whole world, and restrict the other ports "only for your eyes".
so it seem to be working fine.
having said that, i do have a similar problem :)
after working fine for X amount of time, something happens and the instance become unreachable at all, aws health check also shows 1/2.
at first i thought maybe it is a bad HW in aws, as i saw something like that in the past, but after seeing this issue, there might be something else going on.

the maintenance section say "If you run into any problems, a reboot may fix it" and it does, that is actually my usual approach :D 
but it is very unstable at the moment, i might do something stupid like a script to query the instance health check every X minutes and if it is dropping to 1/2 just initiate a reboot.

if you need logs from my sometimes working instance to try to understand what causes the hangups, do let me know.

**Comment by t3chn0m4g3** [comment]
Can you check if your Swap is filling up? See #476

**Comment by simonk9** [comment]
> Can you check if your Swap is filling up? See #476

hi, i dont have the cockpit-pcp pcp packages.
also when running:
`for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r | less`

i dont see the the problematic process "pmproxy".

so it must be something else causing it to hang.

**Comment by austinJayIves** [comment]
Yesterday, I encountered an issue, which was very similar to the one described here. I seem to have resolved it, and wanted to share how.

Checking the install.log (line ~7430) I found this:

> Setting up grub-pc (2.04-3) ...
Installing for i386-pc platform.
grub-install: error: cannot find a GRUB drive for /dev/sda.  Check your device.map.
Generating grub configuration file ...

Looking at my AWS instance, I noticed that `/dev/sda` does not exist. Our AWS instances map their primary drive to `/dev/nvme0n1`.

I executed `grub-install --target=i386-pc --recheck /dev/nvme0n1; update-grub` to ensure that grub was installed and working. 

Additionally, to be safe I also followed the steps outlined in #406, executing `sysctl --system` at the end as well.

Ultimately it looks like this has fixed the issue we've had with deploying in AWS. I've deployed 3 honeypots this way, all of them appear to be working, 12 hours in.

**Comment by t3chn0m4g3** [comment]
@austinJayIves Thank you for sharing this info. For my peace of mind, you did run a [T-Pot Post Install](https://github.com/dtag-dev-sec/tpotce#postinstall)?
On installation I leave the device map and bootloader location untouched, so there seems to be a hickup within the AMIs happening when migrating to SID.
Can you send me the `/install.err` and `/install.log` for a machine, just drag / drop in here.

**Comment by t3chn0m4g3** [comment]
Any updates on this?

**Comment by austinJayIves** [comment]
Hey @t3chn0m4g3, Here are the `install.log` and `install.err` files for the installation associated with my comments. 

I was asked to scrub any IPs/Hostnames associated with the honeypot from the logs before submitting, but this is the only change that has been made to the log. (Lines 12628-12631 were affected by this). A .txt extension was added to `install.err` to make github happier.

I installed on the Debian 9 AMI provided to AWS by Debian, and you are correct, I ran a T-Pot Post Install (with type=auto and a configuration to install the NEXTGEN profile). 
The only additional steps I took were those described in my post above.

FIles:
[install.log](https://github.com/dtag-dev-sec/tpotce/files/3888202/install.log) [install.err](https://github.com/dtag-dev-sec/tpotce/files/3888208/install.err.txt)

**Comment by t3chn0m4g3** [comment]
Logs LGTM. Guess a wait for finalized AMIs is unavoidable.

**Comment by simonk9** [comment]
i tried some of the proposed solutions and still observed random freezes.
didn't check logs, but my instance also didn't had sda it was xvda (GP SSD), grub install on it didn't help.
also the sysctl to disable ipv6 didn't help.
in the other thread it was suggested to set static ip assignment and not dhcp, not sure what i did wrong, but networking restart failed, according to log it didn't manage to bring eth0 up, but i thought it is a mistake because you need to first to take it down to bring it up... so i rebooted the instance and i had to terminate it because it wasn't accessible at all after reboot with static config.

**Comment by t3chn0m4g3** [comment]
Follow up [here](https://wiki.debian.org/Cloud/AmazonEC2Image) for status on official Buster AMIs for AWS.

Closing this for now, happy to reopen if someone does a PR for the latest AMIs.
