### ISSUE TITLE
enhancement request:  Please capture all these helpful reporting scripts somewhere!

### ISSUE THREAD

**Issue by workandresearchgithub** [dtag-dev-sec/tpotce#503]
I came across this recently:

--
I am not sure if this is what you want ... It will however give you the top IPs in descending order.

```
#!/bin/bash
function fuMYTOPIPS {
curl -s -XGET "http://127.0.0.1:64298/_search" -H 'Content-Type: application/json' -d'
{
  "aggs": {
    "ips": {
      "terms": { "field": "src_ip.keyword", "size": 5 }
      }
    },
  "size" : 0
  }'
}

fuMYTOPIPS | jq '.aggregations.ips.buckets[].key' | tr -d '"'
```

You can increase the size to a fitting value, however limitations of the [ES search, aggs and query APIs](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search.html) apply.

_Originally posted by @t3chn0m4g3 in https://github.com/dtag-dev-sec/tpotce/issues/379#issuecomment-495954405_

--

Please consider collecting / capturing all these reporting type snippets somewhere for folks (like me) that are attempting to implement t-pot in a production environment, but might not have the REST API / CURL / development expertise that others have.  You may consider this a trivial bit of code, and perhaps to folks with your expertise it is, but for many of us, we might be unaware this capability exists, or the experience to get started.  These types of reporting snippets are really  helpful / valuable!  Much thanks for sharing it!   

p.s.  see attached for my first contribution.  

[topIPs.sh.txt](https://github.com/dtag-dev-sec/tpotce/files/4003420/topIPs.sh.txt)

**Comment by t3chn0m4g3** [comment]
Thanks for the nice words and the contribution. I added the `documentation` tag to the original issue. Issues labeled with this tag usually contain the sort of information you are referring to, in this case I forgot :bowtie: 
The reason I am hesistant to add snippets like this to the script collection is that proof of concepts usually only work for a limited time period since the ELK APIs are changing too rapidly.
Bsesides, this is outside of the usual T-Pot usage scope where I can only recommend to read up on the documentation on the tools being used for T-Pot (link list when opening up a new issue).
