### ISSUE TITLE
waiting for services...

### ISSUE THREAD

**Issue by luck00** [dtag-dev-sec/tpotce#51]
Hello,

I am using t-pot 16.03 and after a while (one week) it is not working anymore, the status.sh command display waiting for services.........  services are busy or not available....etc

Thank you.

**Comment by t3chn0m4g3** [comment]
please run `sudo dcres.sh` and `sudo reboot`.

**Comment by luck00** [comment]
After I run dcres.sh

cowrie stop/waiting
dionaea stop/waiting
stop: Unknown instance:
stop: Unknown instance:
stop: Unknown instance:
stop: Unknown instance:
stop: Unknown instance:
### Waiting 10 seconds before restarting docker ...
docker stop/waiting
docker start/running, process 8290
WARNING: No swap limit support
Docker daemon is now available.
### Docker is now up and running again.
### Removing obsolete container data ...
a40b7e87aca5
005c008bc70c
e126b4d81572
8e55a1e904b9
008a914160d4
739a58d3d8cc
bc1aaeda9570
### Removing obsolete image data ...
docker: "rmi" requires a minimum of 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
### Starting T-Pot services ...
cowrie start/running, process 8411

And stay here long time....

**Comment by t3chn0m4g3** [comment]
It is a known issue with `upstart` and should be resolved with T-Pot 16.10 which uses `systemd`.

You can try ...

```
sudo su -
service docker stop
apt-get purge docker-engine
rm -rf /var/lib/docker
rm /var/run/check.lock
apt-get install docker-engine
service docker start
update-images.sh
```

... but since you did not provide the necessary details we kindly ask for when opening a new issue this is just my best guess :bowtie: 

If apt-get asks you to overwrite `/etc/default/docker` you select **N**

If the problem still persists I kindly ask you to reinstall or try the [16.10](https://github.com/dtag-dev-sec/tpotce/tree/16.10) branch to check if that fixes your problem.

**Comment by luck00** [comment]
Now it is working... Thank you very much.

**Comment by t3chn0m4g3** [comment]
Welcome :smile:
