### ISSUE TITLE
How often do Suricata Rules update?

### ISSUE THREAD

**Issue by PSparker** [dtag-dev-sec/tpotce#518]
Currently running T-POT 19.03 on a virtalbox instance and I'd like to know how often the suricata rules are updated from emerging threats?

I specifically looking for attacks against citrix CVE-2019-19781, I have run some tests against my TPOT instance but i do not see anything in Suricata flag for

> 2029206 - ET EXPLOIT Possible Citrix Application Delivery Controller Arbitrary Code Execution Attempt (CVE-2019-19781)

which has been available since December in EmergingThreats exploit rules.

**Comment by t3chn0m4g3** [comment]
Rules are updated on container [start](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/dist/update.sh), but this will only work if T-Pot is allowed to directly communicate with the internet.
However it is unlikely you will see anything within Suricata, since the probe will fail as no vulnerable Netscaler instance is available within T-Pot, hence the exploit code will not be executed and subsequently not identified by Suricata.

**Comment by PSparker** [comment]
> 
> 
> Rules are updated on container [start](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/dist/update.sh), but this will only work if T-Pot is allowed to directly communicate with the internet.
> However it is unlikely you will see anything within Suricata, since the probe will fail as no vulnerable Netscaler instance is available within T-Pot, hence the exploit code will not be executed and subsequently not identified by Suricata.

Many thanks for the quick response. In that case I'll continue to run with [MalwareTech's Citrix Honeypot](https://github.com/MalwareTech/CitrixHoneypot).

**Comment by t3chn0m4g3** [comment]
Just integrated CitrixHoneypot, see Changelog for details.
