### ISSUE TITLE
Feature Request: Enable blocking of certain IP's

### ISSUE THREAD

**Issue by Patrik-Hansson** [dtag-dev-sec/tpotce#542]
Hi
My T-Pot is being hammered by one specific ip range and I'v lost interest in that traffic.
Would it be possible to have a file that contains source ip's and get picked up by T-Pot when it starts so it get added to iptables and blocked ?
I added the rules manually with the following but they wont survive the reboot.
iptables -I DOCKER-USER -s 5.188.86.0/24 -j DROP

**Comment by t3chn0m4g3** [comment]
You need to put this in the rule script `/opt/tpot/bin/rules.sh`.

**Comment by Patrik-Hansson** [comment]
Ok.
Would it (meaning you :) ) be possible to extend it so that rules.sh imports it from another file so that it doesn't get overwritten by update.sh ?

**Comment by t3chn0m4g3** [comment]
I understand, but I have to decline. At this point I am more looking into reducing host dependencies T-Pot is relying on in order to make T-Pot ready for other linux distros.
Please use other resources on your host for compensation i.e. `/etc/rc.local` if you do not want modifications on the rules script.
Thanks for understanding :bowtie:

**Comment by Patrik-Hansson** [comment]
No problem, totally understand.
