### ISSUE TITLE
Adding Honeypots

### ISSUE THREAD

**Issue by sphereict** [dtag-dev-sec/tpotce#55]
Hi

I would just like to know if the following is possible. 
I would like to deploy T-pot in some of our data centers nationally and would like to get feeds directly from the other T-pots to the main one in our office. Something in the line of the T-pot in our office acting as a master the the other T-Pots acting as slaves. 

Can this be done if so can you provide a tut or a guide on how to set it up.

Regards
Gerhard
# Contribution

Thank you for your decision to contribute to T-Pot.
## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [x] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [x] Check the [FAQ](#faq)
- [x] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:
## 

<a name="faq"></a>
## 

<a name="info"></a>
### Baisc support information
- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
### Experimental outline

This can be done, but it is not possible out of the box and you should wait for the 16.10 release. Please understand that the following information can only outline the basics and I will try to find the time for some proper documentation in the future :innocent: 

The only portions you have to change is the logstash configuration within the ELK container and forward the logs to a central Elasticsearch instance (maybe [Beats](https://www.elastic.co/de/products/beats) is even better suited) which can receive on tcp/9200 (If this would be another T-Pot you should disable all honeypot services to avoid port conflicts, also that machine should have serious horsepower, 32GB RAM, 256GB+ SSD, 4 CPU cores, depending on your traffic expectations). But be careful, Elasticsearch should not be exposed directly to untrusted networks since it does not come with its own authentication. You should either put a reverse proxy with cert based or at least basic auth in front of it or use [shield](https://www.elastic.co/de/products/shield). 

Please read up on the following issues and the logstash documentation which are covering some similar topics and should help you getting started:
#41 
#50 
https://github.com/dtag-dev-sec/elk/pull/4
[Logstash documentation](https://www.elastic.co/guide/en/logstash/current/output-plugins.html)

### Basic steps:
1. Install your T-Pot 16.10 (release mid / end of October, ***not dev***) instaces
2. Install your central ELK instance (protect Elasticsearch)
3. Git clone `git clone https://github.com/dtag-dev-sec/elk`
4. Modify `elk/dist/conf/logstash.conf` to fit your environment (output section):
```
# Output section
output {
  elasticsearch {
    hosts => ["<your ip>:9200"]
  }

  # Debug output
  #stdout {
  #  codec => rubydebug
  #}
```
Finally copy the modified `logstash.conf` to `/data/elk/logstash/conf` and `reboot`

**Comment by sphereict** [comment]
HI Mark

Thanks for your reply. So it will be best to then wait for the new release. Will it be simple to deploy an agent then ?

Looking forward to your reply.

Sincerely.

[cid:image002.png@01D20759.EB5EFB80]

**Comment by t3chn0m4g3** [comment]
The new release will improve some things and include the examples. However it will remain a manual process as described in this issue.

**Comment by t3chn0m4g3** [comment]
T-Pot 16.10 contains the necessary basics to cover this request.

**Comment by kesaco-droid** [comment]
Hi, thanks for all these informations. 
@t3chn0m4g3 When you say TPOT contains the necessary basis, could you explain how ? With hpfeeds ? Or by collecting all the logs in the data folder ?  
Sorry, i am just discovering the solution and would like to use it the right way. 
TPOT is really an amazing solution and we can't thank you enough for all the work  and time you invested in this projet.

**Comment by iukea1** [comment]
Also just as a heads up you do want these boxes in an incredibly isolated zone that is extremely locked down.

Have seen a couple people get out of my honeypots and drop to the host :D
