### ISSUE TITLE
How to claim multiple IP addresses?

### ISSUE THREAD

**Issue by cudor** [dtag-dev-sec/tpotce#56]
Dear T-Pot team,

we'd like to use T-Pot as an internal honeypot in our organization. The intention is to forward all unused IP address ranges to the honeypot. In our tests, T-Pot only answered to connections to its own IP address. Is it possible to make T-Pot claim arbitrary IP addresses?

### Baisc support information
- What T-Pot version are you currtently using? 16.03
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? Not that long :-)
- Did you install any upgrades or packages? Yes, we installed farpd, a fake ARP reply daemon.
- Did you modify any scripts? No
- Have you turned persistence on/off? No

Thanks

**Comment by t3chn0m4g3** [comment]
The best idea I am currently having is to put T-Pot behind a firewall and perform a destination NAT from the unused IP addresses to the one of T-Pot.

`farpd` is probably not enough since the packets also need to be forwarded to the internal docker network which uses its own set of `iptables` rules which are dynamically created when a container instance is started. To avoid problems I'd recommend to remove `farpd`.

**Comment by hmlio** [comment]
Hi!

Just to share some config that I have been using to utilize many many IPs in a single honeypot since about 2007 :-)

Let's say your uplink router's IP is 1.1.1.1 and your Honeypot's IP is 1.1.1.2.

Let's also say your additional address space is 192.168.0.0/16.

On your uplink router, route your additional Honeynet network  to 1.1.1.2:
192.168.0.0/16 -> gateway 1.1.1.2 (the Honeypot).

Now you just need to make sure that the Honeypot server knows what to to with traffic that arrives for the 192.168.0.0/16 network:
* Enable routing via `sysctl -w net.ipv4.ip_forward=1`
* Add the network to the loopback interface via `ip addr add dev lo 192.168.0.0/16 scope host`

By using this "trick" you will not need to create thousands of subinterfaces and you will also not fill up your uplink router's ARP table.

All IPs in the network 192.168.0.0/16 will be reachable network wise (i.e. answer to a ping etc.) and can also be used as source IP for traffic initiated by the Honeypot itself (necessary to download malware via http/ftp for instance).

This method worked for my T-POT instance out of the box without any modification to iptables.

To make the entries survive a reboot add  `net.ipv4.ip_forward=1` to your `/etc/sysctl.conf`and modify `/etc/network/interfaces` to contain the following:
<pre><code>auto lo 
iface lo inet loopback
 post-up /sbin/ip addr add dev lo 192.168.0.0/16 scope host</code></pre>
 
Hope this helps!

Cheers,

Emre

**Comment by t3chn0m4g3** [comment]
Awesome! Thank you!

**Comment by t3chn0m4g3** [comment]
@cudor Is this working now for you?

**Comment by cudor** [comment]
Emre's solution is working for us. Thanks for the great support!

**Comment by LandonStewart** [comment]
For Netplan:

- Configure ip forwarding:
```
sysctl -w net.ipv4.ip_forward=1
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
```
- Edit /etc/netplan/01-netcfg.yaml
- Add IP addresses to `lo` (The last two lines are the new ones.  Pay attention to indenting.)
```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0f0:
      addresses: [ 67.xxx.xxx.xxx/27 ]
      gateway4: 67.xxx.xxx.yyy
      nameservers:
          search: [ my.domain.name.com ]
          addresses:
              - "8.8.8.8"
              - "8.8.4.4"
    lo:
      addresses: [ 174.xxx.xxx.xxx/30 ]
```
- `systemctl restart NetworkManager.service`
- Check to see if it's working:
```
# ip addr | grep xxx.xxx.xxx.xx
    inet xxx.xxx.xxx.xxx/30 scope global lo
```
