### ISSUE TITLE
Problem T-Pot-SSH tunneling  with OpenSSH

### ISSUE THREAD

**Issue by RenzoYac** [dtag-dev-sec/tpotce#59]
hello 

I am problem in my conection ssh, with verification code and pasword 

Windows 7 cmd

C:\Users\Administrador\.ssh>ssh -l tsec -p 64295 -L8080:127.0.0.1:64296 192.168.2.24
Verification code:
Password:
Verification code:
Password:
Verification code:
Password:
Permission denied (publickey,keyboard-interactive).

helpme

**Comment by t3chn0m4g3** [comment]
Based on the output I can only guess what the problem is.

Did you enable [2FA](https://www.youtube.com/watch?v=6GmIxVJ6eAQ) and using your correct **tsec** password along with the correct **tokencode**?

**Comment by RenzoYac** [comment]
Yes, I do.

The problem is, I not have the "private key in mi home folder".
How generate?
id_rsa
t3chn0m4g3.ppk

 in the video does not explain.

**Comment by t3chn0m4g3** [comment]
The video does not explain it since it is not the default of T-Pot, which uses two-factor authentication based on google-authenticator.

If you want to use public key authentication, please follow this [guide](https://help.ubuntu.com/community/SSH/OpenSSH/Keys)

Please understand that we cannot cover all details and since this is not a T-Pot related issue I will close it.
