### ISSUE TITLE
It would be great to add the ability to install tpotce on CentOS\RHEL OS

### ISSUE THREAD

**Issue by trust1345** [dtag-dev-sec/tpotce#621]
It would be great to add the ability to install tpotce on CentOS\RHEL OS.
First version (quick and dirty, but work) of script to install on CentOS\RHEL 7 in attach.
There 's a problem with the cockpit start. After the host is restarted, it must be restarted manually (via systemctl).
[install.sh.txt](https://github.com/dtag-dev-sec/tpotce/files/4533661/install.sh.txt)
[run-first.sh.txt](https://github.com/dtag-dev-sec/tpotce/files/4533662/run-first.sh.txt)

**Comment by t3chn0m4g3** [comment]
Thank you, however T-Pot itself will remain on Debian. We are only a small team and supporting multiple distros, especially with regard to the ISO based installation is time we rather invest in increasing the quality of T-Pot. Thanks for understanding.

**Comment by trust1345** [comment]
Thanks for the answer.
I 've made my repository with these files and I might make them better later.

Maybe make a note in a wiki (about the possibility of installation on CentOS\RHEL 7.x) with the explanation that you remove responsibility for its work?
https://github.com/trust1345/tpotce_rhel
And to close issue.

**Comment by t3chn0m4g3** [comment]
We have to discuss / check if we can endorse third party repos.

**Comment by Fosocles** [comment]
A bit of an off-topic, but why CentOS\RHEL?

**Comment by t3chn0m4g3** [comment]
The problem with linking or endorsing a third party repo is that we can neither test or guarantee that T-Pot will run / work as it is supposed to. Even today we have lots of issues caused by installing T-Pot in different regions (problems with mirrors) or people not taking their time to read the documentation or even search previous issues for a solution.
Thanks for your community drive contribution and for your efforts to make T-Pot available within #Redhat #Fedora #CentOS however please understand our decision. The issues will always reflect the link to your repo and if being asked we will reference to this issue.
Thank you.
