### ISSUE TITLE
dps.sh shows everything Down

### ISSUE THREAD

**Issue by BabarAli93** [dtag-dev-sec/tpotce#631]
I installed T-Pot in Debian Buster and solved all library dependency issues including ethtool, docker, docker-compose, and yq. The status of T-Pot is active running. However, every service is DOWN in dps.sh. Please have a look and help me to sort this issue out.

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
<img width="573" alt="Screenshot 2020-05-09 at 7 37 43 AM" src="https://user-images.githubusercontent.com/50677432/81462190-26499800-91ca-11ea-84d8-824044aac0fd.png">

- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
In Vmware. with 2GB Ram and 20GB hard disk
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
there were problems but took help from solved issues and all of them were sorted out
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
just installed the tpot. did not update any package
- Did you modify any scripts or configs? If yes, please attach the changes.
No

- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
<img width="434" alt="Screenshot 2020-05-09 at 7 49 17 AM" src="https://user-images.githubusercontent.com/50677432/81462229-7d4f6d00-91ca-11ea-8fc0-67ece75ed959.png">

- What is the current container status (`dps.sh`)?
Every service Down
<img width="584" alt="Screenshot 2020-05-09 at 7 32 18 AM" src="https://user-images.githubusercontent.com/50677432/81462284-e6cf7b80-91ca-11ea-9a52-7b494a2a058f.png">

- What is the status of the T-Pot service (`systemctl status tpot`)?
Active Running
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
<img width="571" alt="Screenshot 2020-05-09 at 7 41 29 AM" src="https://user-images.githubusercontent.com/50677432/81462253-a96aee00-91ca-11ea-9598-79b0299cb69a.png">

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

I installed tpot in Debian Buster and solved all library dependency issue including ethtool, docker, docker-compose, and yq. The status of T-Pot is active running. However, every service is DOWN. Please have a look and help me to sort this issue out.

**Comment by t3chn0m4g3** [comment]
Dependency issues are a clear sign of repos not being reachable during installation which is usually caused if the installer cannot access all resources.
You did not provide logs which is essential to determine what went wrong or is missing.

**Comment by BabarAli93** [comment]
Where can I find these log files in the project. Can we navigate me through the path? 
tpotce/etc or tpotce/bin??

**Comment by BabarAli93** [comment]
bro find the screenshots of install.log


![01](https://user-images.githubusercontent.com/50677432/81476782-2f1f8580-922d-11ea-831c-2aa4375627d6.JPG)
![02](https://user-images.githubusercontent.com/50677432/81476787-32b30c80-922d-11ea-8ea0-6d1c8764b38f.JPG)
![03](https://user-images.githubusercontent.com/50677432/81476788-33e43980-922d-11ea-8c9f-c3cab32986cf.JPG)
![04](https://user-images.githubusercontent.com/50677432/81476789-35156680-922d-11ea-9f76-e2728bfe145a.JPG)
![05](https://user-images.githubusercontent.com/50677432/81476791-36df2a00-922d-11ea-917f-4b3badbcec22.JPG)
![06](https://user-images.githubusercontent.com/50677432/81476794-39418400-922d-11ea-9199-6d3e421ebc8b.JPG)
![07](https://user-images.githubusercontent.com/50677432/81476796-3c3c7480-922d-11ea-9d2f-368702feaa07.JPG)
![08](https://user-images.githubusercontent.com/50677432/81476799-3e063800-922d-11ea-8eaf-a0c8225f96d5.JPG)
![09](https://user-images.githubusercontent.com/50677432/81476801-3fcffb80-922d-11ea-8630-acf5aaca5e30.JPG)
![10](https://user-images.githubusercontent.com/50677432/81476804-4199bf00-922d-11ea-8b18-b31ef09e60fa.JPG)

**Comment by t3chn0m4g3** [comment]
The automatic mirror selection failed, first screenshot, good hint for your router blocking some outgoing traffic. The installer went own with default repos, however I need /install.err for more details.

**Comment by gregtampa** [comment]
`[root@necessarymiddle:/]# cat install.err
info: Trying to set 'docker.io/restart' [boolean] to 'true'
info: Loading answer for 'docker.io/restart'
info: Trying to set 'debconf/frontend' [select] to 'noninteractive'
info: Loading answer for 'debconf/frontend'
W: --force-yes is deprecated, use one of the options starting with --allow instead.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
debconf: delaying package configuration, since apt-utils is not installed
Adding password for user mobman
Generating a RSA private key
....................................................+++
...+++
writing new private key to '/data/nginx/cert/nginx.key'
-----
npm WARN npm npm does not support Node.js v10.23.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.20 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
Cloning into '/opt/tpot'...
Created symlink /etc/systemd/system/multi-user.target.wants/tpot.service → /etc/systemd/system/tpot.service.
Usage: usermod [options] LOGIN

Options:
  -c, --comment COMMENT         new value of the GECOS field
  -d, --home HOME_DIR           new home directory for the user account
  -e, --expiredate EXPIRE_DATE  set account expiration date to EXPIRE_DATE
  -f, --inactive INACTIVE       set password inactive after expiration
                                to INACTIVE
  -g, --gid GROUP               force use GROUP as new primary group
  -G, --groups GROUPS           new list of supplementary GROUPS
  -a, --append                  append the user to the supplemental GROUPS
                                mentioned by the -G option without removing
                                him/her from other groups
  -h, --help                    display this help message and exit
  -l, --login NEW_LOGIN         new value of the login name
  -L, --lock                    lock the user account
  -m, --move-home               move contents of the home directory to the
                                new location (use only with -d)
  -o, --non-unique              allow using duplicate (non-unique) UID
  -p, --password PASSWORD       use encrypted password for the new password
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             new login shell for the user account
  -u, --uid UID                 new UID for the user account
  -U, --unlock                  unlock the user account
  -v, --add-subuids FIRST-LAST  add range of subordinate uids
  -V, --del-subuids FIRST-LAST  remove range of subordinate uids
  -w, --add-subgids FIRST-LAST  add range of subordinate gids
  -W, --del-subgids FIRST-LAST  remove range of subordinate gids
  -Z, --selinux-user SEUSER     new SELinux user mapping for the user account

sed: can't read /etc/default/grub: No such file or directory
sed: can't read /etc/default/grub: No such file or directory
./install.sh: line 837: update-grub: command not found
./install.sh: line 844: update-initramfs: command not found
Trying: dig +short myip.opendns.com @resolver2.opendns.com
`

**Comment by sudeyuksek** [comment]
@BabarAli93 @gregtampa  Could you find any solutions for this ? I have exactly the same issue
![image](https://user-images.githubusercontent.com/60464361/177208307-7acdca34-f4c9-48cd-b01d-72c6ee386bcf.png)
