### ISSUE TITLE
docker is not installed and all container are down

### ISSUE THREAD

**Issue by lemorn** [dtag-dev-sec/tpotce#682]
Hello! I have encountered some problems. I downloaded the latest tpot20.06 from github and imported it into vmware workstation as a mirror. But it shows that docker is not installed and all containers are down. I see from other issues that this problem can be solved by opening ICMP outbound, but how should I do it (my computer is a windows10 system, and the vmware used is vmware workstation 15 pro 15.5.2)?

There are two more problems. I want to enter root mode through the su command, but it fails after entering the password;

My computer is on the intranet, can I use tpot?

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
![image](https://user-images.githubusercontent.com/53805865/89854085-8a169f00-dbc5-11ea-93e0-4ec7cdb5e7fa.png)
![image](https://user-images.githubusercontent.com/53805865/89854110-9d296f00-dbc5-11ea-9a59-13f912143629.png)

- What T-Pot version are you currently using?
  20.06
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
  Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
  Vmware workstation pro
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
 1 day
- Did you install upgrades, packages or use the update script?
  no
- Did you modify any scripts or configs? If yes, please attach the changes.
  no
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/53805865/89854409-6a33ab00-dbc6-11ea-8d82-13cac31532a1.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/53805865/89854537-b7b01800-dbc6-11ea-98bd-b11dcb3a8ef1.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/53805865/89854581-d31b2300-dbc6-11ea-9aa3-c8e9d1740a82.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/53805865/89854633-f6de6900-dbc6-11ea-9f13-299cddf2af14.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
The screenshots you provided show the installation failed because of the installation requirements probably not being met.
To find the best and fastetest Debian mirrors the T-Pot ISO installer relies on [netselect-apt](https://manpages.debian.org/stretch/netselect-apt/netselect-apt.1.en.html), hence the ICMP requirement. If this fails it will fallback to the Debian standard [mirror](https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/install.sh#L290-L307).
If this does not work for you, you can always follow the instructions in the Readme for a [post installation](https://github.com/dtag-dev-sec/tpotce#postinstall).
Installing T-Pot requires transparent access to the internet, if you are installing from a corporate environmnet it is likely you need to proxy the connection and set the corresponding environment variables, please check the Debian documentation for that.
